# This file contains converted modifiers
ABILITY_CHARM = Modifier(args=None, className='HiddenAbilityRateBoosterModifier', player=True, stackCount=100, typeId='ABILITY_CHARM')
AMULET_COIN = Modifier(args=None, className='MoneyMultiplierModifier', player=True, stackCount=100, typeId='AMULET_COIN')
ATTACK_TYPE_BOOSTER0 = Modifier(args=[None, 0, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[0])
ATTACK_TYPE_BOOSTER1 = Modifier(args=[None, 1, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[1])
ATTACK_TYPE_BOOSTER10 = Modifier(args=[None, 10, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[10])
ATTACK_TYPE_BOOSTER11 = Modifier(args=[None, 11, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[11])
ATTACK_TYPE_BOOSTER12 = Modifier(args=[None, 12, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[12])
ATTACK_TYPE_BOOSTER13 = Modifier(args=[None, 13, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[13])
ATTACK_TYPE_BOOSTER14 = Modifier(args=[None, 14, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[14])
ATTACK_TYPE_BOOSTER15 = Modifier(args=[None, 15, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[15])
ATTACK_TYPE_BOOSTER16 = Modifier(args=[None, 16, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[16])
ATTACK_TYPE_BOOSTER17 = Modifier(args=[None, 17, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[17])
ATTACK_TYPE_BOOSTER2 = Modifier(args=[None, 2, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[2])
ATTACK_TYPE_BOOSTER3 = Modifier(args=[None, 3, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[3])
ATTACK_TYPE_BOOSTER4 = Modifier(args=[None, 4, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[4])
ATTACK_TYPE_BOOSTER5 = Modifier(args=[None, 5, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[5])
ATTACK_TYPE_BOOSTER6 = Modifier(args=[None, 6, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[6])
ATTACK_TYPE_BOOSTER7 = Modifier(args=[None, 7, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[7])
ATTACK_TYPE_BOOSTER8 = Modifier(args=[None, 8, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[8])
ATTACK_TYPE_BOOSTER9 = Modifier(args=[None, 9, 20], className='AttackTypeBoosterModifier', player=True, stackCount=100, typeId='ATTACK_TYPE_BOOSTER', typePregenArgs=[9])
BASE_STAT_BOOSTER0 = Modifier(args=[None, 0], className='PokemonBaseStatModifier', player=True, stackCount=100, typeId='BASE_STAT_BOOSTER', typePregenArgs=[0])
BASE_STAT_BOOSTER1 = Modifier(args=[None, 1], className='PokemonBaseStatModifier', player=True, stackCount=100, typeId='BASE_STAT_BOOSTER', typePregenArgs=[1])
BASE_STAT_BOOSTER2 = Modifier(args=[None, 2], className='PokemonBaseStatModifier', player=True, stackCount=100, typeId='BASE_STAT_BOOSTER', typePregenArgs=[2])
BASE_STAT_BOOSTER3 = Modifier(args=[None, 3], className='PokemonBaseStatModifier', player=True, stackCount=100, typeId='BASE_STAT_BOOSTER', typePregenArgs=[3])
BASE_STAT_BOOSTER4 = Modifier(args=[None, 4], className='PokemonBaseStatModifier', player=True, stackCount=100, typeId='BASE_STAT_BOOSTER', typePregenArgs=[4])
BASE_STAT_BOOSTER5 = Modifier(args=[None, 5], className='PokemonBaseStatModifier', player=True, stackCount=100, typeId='BASE_STAT_BOOSTER', typePregenArgs=[5])
BERRY0 = Modifier(args=[None, 0], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[0])
BERRY1 = Modifier(args=[None, 1], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[1])
BERRY10 = Modifier(args=[None, 10], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[10])
BERRY2 = Modifier(args=[None, 2], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[2])
BERRY3 = Modifier(args=[None, 3], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[3])
BERRY4 = Modifier(args=[None, 4], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[4])
BERRY5 = Modifier(args=[None, 5], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[5])
BERRY6 = Modifier(args=[None, 6], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[6])
BERRY7 = Modifier(args=[None, 7], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[7])
BERRY8 = Modifier(args=[None, 8], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[8])
BERRY9 = Modifier(args=[None, 9], className='BerryModifier', player=True, stackCount=100, typeId='BERRY', typePregenArgs=[9])
BERRY_POUCH = Modifier(args=None, className='PreserveBerryModifier', player=True, stackCount=100, typeId='BERRY_POUCH')
CANDY_JAR = Modifier(args=None, className='LevelIncrementBoosterModifier', player=True, stackCount=100, typeId='CANDY_JAR')
DYNAMAX_BAND = Modifier(args=None, className='GigantamaxAccessModifier', player=True, stackCount=100, typeId='DYNAMAX_BAND')
EXP_BALANCE = Modifier(args=None, className='ExpBalanceModifier', player=True, stackCount=100, typeId='EXP_BALANCE')
EXP_CHARM = Modifier(args=[25], className='ExpBoosterModifier', player=True, stackCount=100, typeId='EXP_CHARM')
EXP_SHARE = Modifier(args=None, className='ExpShareModifier', player=True, stackCount=100, typeId='EXP_SHARE')
FOCUS_BAND = Modifier(args=[None], className='SurviveDamageModifier', player=True, stackCount=100, typeId='FOCUS_BAND')
FORM_CHANGE_ITEM = Modifier(args=[None, None, True], className='PokemonFormChangeItemModifier', player=True, stackCount=100, typeId='FORM_CHANGE_ITEM', typePregenArgs=[None])
GOLDEN_EGG = Modifier(args=[None, None], className='PokemonExpBoosterModifier', player=True, stackCount=100, typeId='GOLDEN_EGG')
GOLDEN_POKEBALL = Modifier(args=None, className='ExtraModifierModifier', player=True, stackCount=100, typeId='GOLDEN_POKEBALL')
GOLDEN_PUNCH = Modifier(args=[None], className='DamageMoneyRewardModifier', player=True, stackCount=100, typeId='GOLDEN_PUNCH')
GRIP_CLAW = Modifier(args=[None, 10], className='ContactHeldItemTransferChanceModifier', player=True, stackCount=100, typeId='GRIP_CLAW')
HEALING_CHARM = Modifier(args=[1.1], className='HealingBoosterModifier', player=True, stackCount=100, typeId='HEALING_CHARM')
IV_SCANNER = Modifier(args=None, className='IvScannerModifier', player=True, stackCount=100, typeId='IV_SCANNER')
KINGS_ROCK = Modifier(args=[None], className='FlinchChanceModifier', player=True, stackCount=100, typeId='KINGS_ROCK')
LEFTOVERS = Modifier(args=[None], className='TurnHealModifier', player=True, stackCount=100, typeId='LEFTOVERS')
LOCK_CAPSULE = Modifier(args=None, className='LockModifierTiersModifier', player=True, stackCount=100, typeId='LOCK_CAPSULE')
LUCKY_EGG = Modifier(args=[None, None], className='PokemonExpBoosterModifier', player=True, stackCount=100, typeId='LUCKY_EGG')
MEGA_BRACELET = Modifier(args=None, className='MegaEvolutionAccessModifier', player=True, stackCount=100, typeId='MEGA_BRACELET')
MINI_BLACK_HOLE = Modifier(args=[None], className='TurnHeldItemTransferModifier', player=True, stackCount=100, typeId='MINI_BLACK_HOLE')
MULTI_LENS = Modifier(args=[None], className='PokemonMultiHitModifier', player=True, stackCount=100, typeId='MULTI_LENS')
QUICK_CLAW = Modifier(args=[None], className='BypassSpeedChanceModifier', player=True, stackCount=100, typeId='QUICK_CLAW')
REVIVER_SEED = Modifier(args=[None], className='PokemonInstantReviveModifier', player=True, stackCount=100, typeId='REVIVER_SEED')
SHELL_BELL = Modifier(args=[None], className='HitHealModifier', player=True, stackCount=100, typeId='SHELL_BELL')
SHINY_CHARM = Modifier(args=None, className='ShinyRateBoosterModifier', player=True, stackCount=100, typeId='SHINY_CHARM')
SOOTHE_BELL = Modifier(args=[None], className='PokemonFriendshipBoosterModifier', player=True, stackCount=100, typeId='SOOTHE_BELL')
SOUL_DEW = Modifier(args=[None], className='PokemonNatureWeightModifier', player=True, stackCount=100, typeId='SOUL_DEW')
SUPER_EXP_CHARM = Modifier(args=[None], className='ExpBoosterModifier', player=True, stackCount=100, typeId='SUPER_EXP_CHARM')
TEMP_STAT_BOOSTER5 = Modifier(args=[5, 5], className='TempBattleStatBoosterModifier', player=True, stackCount=100, typeId='TEMP_STAT_BOOSTER', typePregenArgs=[5])
WIDE_LENS = Modifier(args=[None, 5], className='PokemonMoveAccuracyBoosterModifier', player=True, stackCount=100, typeId='WIDE_LENS')
